// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v6.30.0
// source: probe.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义 ProbeTaskRequest，包含多个探测任务
type ProbeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*ProbeTask           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"` // 多个探测任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTaskRequest) Reset() {
	*x = ProbeTaskRequest{}
	mi := &file_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTaskRequest) ProtoMessage() {}

func (x *ProbeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTaskRequest.ProtoReflect.Descriptor instead.
func (*ProbeTaskRequest) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeTaskRequest) GetTasks() []*ProbeTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// 定义单个探测任务
type ProbeTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip1           string                 `protobuf:"bytes,1,opt,name=ip1,proto3" json:"ip1,omitempty"` // 源 IP 地址
	Ip2           string                 `protobuf:"bytes,2,opt,name=ip2,proto3" json:"ip2,omitempty"` // 目标 IP 地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTask) Reset() {
	*x = ProbeTask{}
	mi := &file_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTask) ProtoMessage() {}

func (x *ProbeTask) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTask.ProtoReflect.Descriptor instead.
func (*ProbeTask) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeTask) GetIp1() string {
	if x != nil {
		return x.Ip1
	}
	return ""
}

func (x *ProbeTask) GetIp2() string {
	if x != nil {
		return x.Ip2
	}
	return ""
}

// 控制面返回任务执行结果的响应
type ProbeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 返回状态信息，例如 "ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTaskResponse) Reset() {
	*x = ProbeTaskResponse{}
	mi := &file_probe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTaskResponse) ProtoMessage() {}

func (x *ProbeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTaskResponse.ProtoReflect.Descriptor instead.
func (*ProbeTaskResponse) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 定义 ProbeResultRequest，包含多个探测结果
type ProbeResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ProbeResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // 多个探测结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResultRequest) Reset() {
	*x = ProbeResultRequest{}
	mi := &file_probe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResultRequest) ProtoMessage() {}

func (x *ProbeResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResultRequest.ProtoReflect.Descriptor instead.
func (*ProbeResultRequest) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeResultRequest) GetResults() []*ProbeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 定义 ProbeResult，包含探测结果
type ProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip1           string                 `protobuf:"bytes,1,opt,name=ip1,proto3" json:"ip1,omitempty"`                            // 源 IP 地址
	Ip2           string                 `protobuf:"bytes,2,opt,name=ip2,proto3" json:"ip2,omitempty"`                            // 目标 IP 地址
	TcpDelay      int64                  `protobuf:"varint,3,opt,name=tcp_delay,json=tcpDelay,proto3" json:"tcp_delay,omitempty"` // TCP 延迟，单位纳秒
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                // 时间戳，格式为 RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_probe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeResult) GetIp1() string {
	if x != nil {
		return x.Ip1
	}
	return ""
}

func (x *ProbeResult) GetIp2() string {
	if x != nil {
		return x.Ip2
	}
	return ""
}

func (x *ProbeResult) GetTcpDelay() int64 {
	if x != nil {
		return x.TcpDelay
	}
	return 0
}

func (x *ProbeResult) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 数据面向控制面返回探测结果的响应
type ProbeResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 返回状态信息，例如 "ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResultResponse) Reset() {
	*x = ProbeResultResponse{}
	mi := &file_probe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResultResponse) ProtoMessage() {}

func (x *ProbeResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResultResponse.ProtoReflect.Descriptor instead.
func (*ProbeResultResponse) Descriptor() ([]byte, []int) {
	return file_probe_proto_rawDescGZIP(), []int{5}
}

func (x *ProbeResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_probe_proto protoreflect.FileDescriptor

var file_probe_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x22, 0x3a, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x22, 0x2f, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x31, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70,
	0x32, 0x22, 0x2b, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42,
	0x0a, 0x12, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x6c, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x70, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x69, 0x70, 0x32, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x63, 0x70, 0x5f, 0x64, 0x65, 0x6c,
	0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x63, 0x70, 0x44, 0x65, 0x6c,
	0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x2d, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32,
	0x57, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5f, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49,
	0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_probe_proto_rawDescOnce sync.Once
	file_probe_proto_rawDescData []byte
)

func file_probe_proto_rawDescGZIP() []byte {
	file_probe_proto_rawDescOnce.Do(func() {
		file_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_probe_proto_rawDesc), len(file_probe_proto_rawDesc)))
	})
	return file_probe_proto_rawDescData
}

var file_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_probe_proto_goTypes = []any{
	(*ProbeTaskRequest)(nil),    // 0: probe.ProbeTaskRequest
	(*ProbeTask)(nil),           // 1: probe.ProbeTask
	(*ProbeTaskResponse)(nil),   // 2: probe.ProbeTaskResponse
	(*ProbeResultRequest)(nil),  // 3: probe.ProbeResultRequest
	(*ProbeResult)(nil),         // 4: probe.ProbeResult
	(*ProbeResultResponse)(nil), // 5: probe.ProbeResultResponse
}
var file_probe_proto_depIdxs = []int32{
	1, // 0: probe.ProbeTaskRequest.tasks:type_name -> probe.ProbeTask
	4, // 1: probe.ProbeResultRequest.results:type_name -> probe.ProbeResult
	0, // 2: probe.ProbeTaskService.SendProbeTasks:input_type -> probe.ProbeTaskRequest
	3, // 3: probe.ProbeResultService.SendProbeResults:input_type -> probe.ProbeResultRequest
	2, // 4: probe.ProbeTaskService.SendProbeTasks:output_type -> probe.ProbeTaskResponse
	5, // 5: probe.ProbeResultService.SendProbeResults:output_type -> probe.ProbeResultResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_probe_proto_init() }
func file_probe_proto_init() {
	if File_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_probe_proto_rawDesc), len(file_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_probe_proto_goTypes,
		DependencyIndexes: file_probe_proto_depIdxs,
		MessageInfos:      file_probe_proto_msgTypes,
	}.Build()
	File_probe_proto = out.File
	file_probe_proto_goTypes = nil
	file_probe_proto_depIdxs = nil
}
