#协程池协程数量
PoolNum = 10
#接收节点信息端口
ReceivePort = "8080"
#接收探测信息端口号
DetectPort = "8081"
#下发一次探测任务时长
DetectCycle = 30
#redis列表过期 小时计算，在转化
ExpireDuration = 24
#redis计算周期
CalculateCycle = 60
#k条路径
K = 6
#惩罚系数
Theta = 0.1
#路径跳数限制
skip = 3
